"""Cleanup + balanced generation of the quiz question bank. DEV ONLY — refuses
to run unless the target DB name ends in "dev".

Replaces the existing question bank with a balanced 100-question set:
  5 sets (a/b/c/d/None) x 5 topics x 4 questions = 100
  - per set: 20      - per topic: 20      - per (set,topic): 4
  - difficulty rotates the 4th slot per cell -> easy 34 / medium 33 / hard 33

Questions are generated by programmatic templates with COMPUTED correct answers
and computed distractors (modelling common errors), so the bank is internally
correct and evenly balanced across every variable — any imbalance observed in
downstream testing is then a real signal, not a fixture artifact.

Usage (from backend/ with the repo venv):
    python -m scripts.seed_questions            # wipe + regenerate (default)
    python -m scripts.seed_questions --dry-run  # print the distribution only
    python -m scripts.seed_questions --seed 7   # reproducible variant
"""
from __future__ import annotations

import argparse
import random
from collections import Counter
from datetime import datetime, timezone
from math import comb, factorial, gcd, perm
from pathlib import Path

# ── Load .env so MONGO_URL / MONGO_DB are available when run standalone ──────
_REPO_ROOT = Path(__file__).resolve().parents[2]
_ENV_PATH = _REPO_ROOT / ".env"
if _ENV_PATH.exists():
    import os
    for _line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip())

import os  # noqa: E402

TOPICS = [
    "Basic Probability",
    "Conditional Probability",
    "Permutations",
    "Combinations",
    "Statistics",
]
SETS = ["a", "b", "c", "d", None]
DIFFICULTIES = ["easy", "medium", "hard"]


# ── Formatting helpers ───────────────────────────────────────────────────────

def _frac(n: int, d: int) -> str:
    """Reduced fraction as a string; a bare integer when it divides evenly."""
    g = gcd(n, d) or 1
    n, d = n // g, d // g
    return str(n) if d == 1 else f"{n}/{d}"


def _num(x: float) -> str:
    """Format a number, dropping a trailing .0 and rounding to 2 dp otherwise."""
    return str(int(x)) if float(x).is_integer() else str(round(x, 2))


def _finalize(rng: random.Random, text: str, correct: str, distractors: list[str]):
    """Assemble exactly 4 unique labels (one == correct), shuffle, id them a-d."""
    labels = [correct]
    for d in distractors:
        if d not in labels:
            labels.append(d)
        if len(labels) == 4:
            break
    # Last-resort padding so we always emit 4 options (rarely reached — the
    # templates supply 4+ distinct distractors).
    for pad in ("None of the above", "Cannot be determined", "0", "1", "2"):
        if len(labels) == 4:
            break
        if pad not in labels:
            labels.append(pad)
    rng.shuffle(labels)
    ids = ["a", "b", "c", "d"]
    choices = [{"id": ids[i], "label": labels[i]} for i in range(4)]
    return text, choices, ids[labels.index(correct)]


# ── Templates: (topic, difficulty) -> (question_text, choices, correct_id) ────
# Every template computes the correct answer from the drawn parameters and
# offers distractors that model plausible mistakes.

def _bp_easy(rng):
    n = rng.randint(2, 6)  # "less than n" on a fair d6
    fav = n - 1
    correct = _frac(fav, 6)
    d = [_frac(n, 6), _frac(fav, 5), _frac(fav + 1, 6), _frac(max(fav - 1, 1), 6)]
    text = f"A fair six-sided die is rolled once. What is the probability of rolling a number less than {n}?"
    return _finalize(rng, text, correct, d)


def _bp_medium(rng):
    s = rng.randint(2, 12)
    ways = 6 - abs(7 - s)  # # of (d6,d6) outcomes summing to s
    correct = _frac(ways, 36)
    d = [_frac(ways, 12), _frac(ways + 1, 36), _frac(ways, 6), _frac(max(ways - 1, 1), 36)]
    text = f"Two fair six-sided dice are rolled. What is the probability that their sum is {s}?"
    return _finalize(rng, text, correct, d)


def _bp_hard(rng):
    n = rng.randint(3, 6)
    correct = _frac(2**n - 1, 2**n)  # P(at least one head) = 1 - (1/2)^n
    d = [_frac(1, 2**n), _frac(n, 2**n), _frac(2**n - 1, 2 ** (n - 1)), _frac(2 ** (n - 1) - 1, 2 ** (n - 1))]
    text = f"A fair coin is flipped {n} times. What is the probability of getting at least one heads?"
    return _finalize(rng, text, correct, d)


def _cp_easy(rng):
    a = rng.randint(6, 12)       # play soccer
    b = rng.randint(2, a - 1)    # of those, also play tennis
    correct = _frac(b, a)
    d = [_frac(b, a + rng.randint(2, 5)), _frac(a - b, a), _frac(b + 1, a), _frac(max(b - 1, 1), a)]
    text = (f"In a class, {a} students play soccer and {b} of them also play tennis. If a student "
            f"who plays soccer is chosen at random, what is the probability that they also play tennis?")
    return _finalize(rng, text, correct, d)


def _cp_medium(rng):
    r = rng.randint(3, 7)
    g = rng.randint(2, 6)
    correct = _frac(r - 1, r + g - 1)  # P(2nd red | 1st red), no replacement
    d = [_frac(r, r + g - 1), _frac(r - 1, r + g), _frac(r - 1, r + g - 2), _frac(r, r + g)]
    text = (f"A bag contains {r} red and {g} green marbles. Two marbles are drawn without replacement. "
            f"Given that the first is red, what is the probability that the second is also red?")
    return _finalize(rng, text, correct, d)


def _cp_hard(rng):
    r = rng.randint(3, 6)
    g = rng.randint(2, 5)
    tot = r + g
    at_least_one_red = comb(tot, 2) - comb(g, 2)
    correct = _frac(comb(r, 2), at_least_one_red)  # P(both red | at least one red)
    d = [
        _frac(comb(r, 2), comb(tot, 2)),
        _frac(r - 1, tot - 1),
        _frac(comb(r, 2), comb(tot, 2) - comb(r, 2)),
        _frac(comb(g, 2), comb(tot, 2)),
    ]
    text = (f"A bag contains {r} red and {g} green marbles. Two are drawn without replacement. Given that "
            f"at least one of the two is red, what is the probability that both are red?")
    return _finalize(rng, text, correct, d)


def _pm_easy(rng):
    n = rng.randint(3, 6)
    correct = str(factorial(n))
    d = [str(factorial(n - 1)), str(factorial(n) // 2), str(n * n), str(factorial(n + 1))]
    text = f"In how many different orders can {n} distinct books be arranged on a shelf?"
    return _finalize(rng, text, correct, d)


def _pm_medium(rng):
    n = rng.randint(5, 9)
    correct = str(perm(n, 2))  # ordered pair: president + VP
    d = [str(n * n), str(comb(n, 2)), str(perm(n - 1, 2)), str(perm(n, 3))]
    text = (f"A club has {n} members. In how many ways can they choose a president and a vice-president "
            f"(one person cannot hold both roles)?")
    return _finalize(rng, text, correct, d)


def _pm_hard(rng):
    n = rng.randint(5, 8)
    correct = str(factorial(n - 1))  # circular arrangements
    d = [str(factorial(n)), str(factorial(n - 2)), str(factorial(n - 1) // 2), str(factorial(n) // 2)]
    text = (f"In how many distinct ways can {n} people be seated around a round table, where seatings that "
            f"differ only by rotation are considered the same?")
    return _finalize(rng, text, correct, d)


def _cm_easy(rng):
    n = rng.randint(5, 9)
    k = rng.randint(2, n - 2)
    correct = str(comb(n, k))
    d = [str(comb(n, k - 1)), str(comb(n, k + 1)), str(perm(n, k)), str(factorial(n) // factorial(k))]
    text = f"In how many ways can {k} students be chosen from a group of {n} students (order does not matter)?"
    return _finalize(rng, text, correct, d)


def _cm_medium(rng):
    m = rng.randint(4, 7)
    w = rng.randint(4, 7)
    a = rng.randint(1, 3)
    b = rng.randint(1, 3)
    correct = str(comb(m, a) * comb(w, b))
    d = [
        str(comb(m, a) + comb(w, b)),
        str(comb(m + w, a + b)),
        str(comb(m, b) * comb(w, a)),
        str(comb(m, a) * comb(w, b) * 2),
    ]
    men = "man" if a == 1 else "men"
    women = "woman" if b == 1 else "women"
    text = (f"From {m} men and {w} women, how many committees can be formed that contain exactly "
            f"{a} {men} and {b} {women}?")
    return _finalize(rng, text, correct, d)


def _cm_hard(rng):
    n = rng.randint(6, 10)
    k = rng.randint(2, 4)
    correct = str(comb(n - 1, k - 1))  # committees of k that include a fixed person
    # NOTE: comb(n,k)-comb(n-1,k) == comb(n-1,k-1) (Pascal) == correct, so it is
    # deliberately NOT used as a distractor.
    d = [str(comb(n - 1, k)), str(comb(n, k - 1)), str(comb(n, k)), str(comb(n - 2, k - 1))]
    text = (f"From {n} people, how many committees of {k} people can be formed that must include one "
            f"specific person (say, the team captain)?")
    return _finalize(rng, text, correct, d)


def _stats_values(rng, k, mean):
    """k positive integers with an exact integer mean (zero-sum perturbations)."""
    vals = [mean] * k
    for _ in range(max(k // 2, 1)):
        d = rng.randint(1, 3)
        i, j = rng.sample(range(k), 2)
        vals[i] += d
        vals[j] -= d
    return vals


def _st_easy(rng):
    k = rng.randint(4, 6)
    mean = rng.randint(4, 10)
    vals = _stats_values(rng, k, mean)
    rng.shuffle(vals)
    correct = str(mean)
    total = sum(vals)
    d = [str(total), str(mean + 1), str(mean - 1), str(round(total / (k + 1)))]
    text = f"What is the mean (average) of the data set {vals}?"
    return _finalize(rng, text, correct, d)


def _st_medium(rng):
    k = rng.choice([5, 7])
    vals = sorted(rng.randint(1, 20) for _ in range(k))
    med = vals[k // 2]
    disp = vals[:]
    rng.shuffle(disp)
    correct = str(med)
    d = [str(round(sum(vals) / k)), str(vals[k // 2 - 1]), str(vals[k // 2 + 1]), str(max(vals))]
    text = f"What is the median of the data set {disp}?"
    return _finalize(rng, text, correct, d)


def _st_hard(rng):
    k = rng.choice([4, 5])
    mean = rng.randint(4, 8)
    vals = _stats_values(rng, k, mean)
    var = sum((v - mean) ** 2 for v in vals) / k          # population variance
    correct = _num(var)
    d = [
        _num(var ** 0.5),                                  # std dev
        str(mean),                                         # the mean itself
        _num(sum((v - mean) ** 2 for v in vals) / (k - 1)),  # sample variance
        _num(var + 1),
    ]
    text = (f"What is the population variance of the data set {vals}? "
            f"(variance = the average of the squared deviations from the mean)")
    return _finalize(rng, text, correct, d)


TEMPLATES = {
    "Basic Probability":       {"easy": _bp_easy, "medium": _bp_medium, "hard": _bp_hard},
    "Conditional Probability": {"easy": _cp_easy, "medium": _cp_medium, "hard": _cp_hard},
    "Permutations":            {"easy": _pm_easy, "medium": _pm_medium, "hard": _pm_hard},
    "Combinations":            {"easy": _cm_easy, "medium": _cm_medium, "hard": _cm_hard},
    "Statistics":              {"easy": _st_easy, "medium": _st_medium, "hard": _st_hard},
}


# ── Balanced allocator ───────────────────────────────────────────────────────

def build_bank(seed: int = 0) -> list[dict]:
    """Deterministically build the balanced 100-question bank (no DB)."""
    bank: list[dict] = []
    cell = 0
    for set_id in SETS:
        for topic in TOPICS:
            # 3 base difficulties + a 4th that rotates by cell -> 34/33/33 overall.
            diffs = ["easy", "medium", "hard", DIFFICULTIES[cell % 3]]
            for j, difficulty in enumerate(diffs):
                rng = random.Random(f"{seed}:{cell}:{j}")
                text, choices, correct_id = TEMPLATES[topic][difficulty](rng)
                bank.append({
                    "stem": topic,
                    "subtitle": text,
                    "choices": choices,
                    "correct_choice_id": correct_id,
                    "set": set_id,
                    "difficulty": difficulty,
                    "difficulty_source": "manual",  # keeps the Phase-8 AI judge off them
                    "difficulty_checked": True,
                    "active": True,
                })
            cell += 1
    return bank


def _print_distribution(bank: list[dict]) -> None:
    print(f"total: {len(bank)}")
    print("  by set:       ", dict(Counter(str(q['set']) for q in bank)))
    print("  by topic:     ", dict(Counter(q['stem'] for q in bank)))
    print("  by difficulty:", dict(Counter(q['difficulty'] for q in bank)))
    print("  correct-id spread:", dict(Counter(q['correct_choice_id'] for q in bank)))


def run(db, seed: int) -> tuple[int, int]:
    qcol = db["questions"]
    deleted = qcol.delete_many({}).deleted_count
    bank = build_bank(seed)
    now = datetime.now(timezone.utc)
    for q in bank:
        q["created_at"] = now
    qcol.insert_many(bank)
    return deleted, len(bank)


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean up + regenerate the balanced question bank (dev DB only).")
    parser.add_argument("--seed", type=int, default=0, help="seed for reproducible generation")
    parser.add_argument("--dry-run", action="store_true", help="print the distribution and exit; no DB writes")
    args = parser.parse_args()

    if args.dry_run:
        _print_distribution(build_bank(args.seed))
        return

    db_name = os.environ.get("MONGO_DB", "")
    mongo_url = os.environ.get("MONGO_URL")
    if not db_name.endswith("dev"):
        raise SystemExit(f"Refusing to run against non-dev DB: {db_name!r}")
    if not mongo_url:
        raise SystemExit("MONGO_URL is not set.")

    from pymongo import MongoClient
    db = MongoClient(mongo_url, serverSelectionTimeoutMS=15000)[db_name]
    print(f"Target DB: {db_name}")
    deleted, inserted = run(db, args.seed)
    print(f"Deleted {deleted} existing question(s); inserted {inserted} balanced question(s).")
    _print_distribution(build_bank(args.seed))


if __name__ == "__main__":
    main()
