services:
  backend:
    build: ../backend
    container_name: fastapi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    command: npm run dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  db:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: motivation
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
